### ISSUE TITLE
glassfish/domains/domain1/docroot is not persistent (dataverse logos)

### ISSUE THREAD

**Issue by wilkos-dans** [IQSS/dataverse-kubernetes#65]
The dataverse logos files are stored in glassfish/domains/domain1/docroot/logos, but is not persistent.
If, for some reason, the dataverse pod is re-created, the logos are gone:

```
bash-4.2$ ls -la /opt/dataverse/appserver/glassfish/domains/domain1/docroot
total 24
drwxr-xr-x 1 glassfish glassfish 4096 Jun 11 07:28 .
drwxr-xr-x 1 glassfish glassfish 4096 Jun  6 13:20 ..
-rw-r--r-- 1 glassfish glassfish 4626 Aug 21  2014 index.html
drwxr-xr-x 4 glassfish glassfish 4096 Jun 11 07:28 logos
```

After re-creation of the dataverse pod:

```
bash-4.2$ ls -la /opt/dataverse/appserver/glassfish/domains/domain1/docroot
total 20
drwxr-xr-x 2 glassfish glassfish 4096 Aug 21  2014 .
drwxr-xr-x 1 glassfish glassfish 4096 Jun 11 09:12 ..
-rw-r--r-- 1 glassfish glassfish 4626 Aug 21  2014 index.html
```

**Comment by poikilotherm** [comment]
Hey Wilko,
thanks for opening this issue and providing feedback. :smile: 

Currently I added no support for [branding](http://guides.dataverse.org/en/latest/installation/config.html#branding-your-installation).

From my view on this, customization/branding is a part of configuration. I would really like to avoid more persistance by default, but use a more K8s approach.

IMHO it would make much sense to add an init container for this. That container could check out a git repo or similar with your brandings. Dataverse could be configured to use those files, see docs link above.

What do you think?

**Comment by pdurbin** [comment]
@wilkos-dans hi! @poikilotherm and I started talking about this at http://irclog.iq.harvard.edu/dataverse/2019-06-11 and one thing I wanted to point out is a line I added to http://guides.dataverse.org/en/4.14/installation/advanced.html#multiple-glassfish-servers as a "gotcha" when installing multiple Glassfish servers:

"When users upload a logo for their dataverse using the “theme” feature described in the Dataverse Management section of the User Guide, these logos are stored only on the Glassfish server the user happend to be on when uploading the logo. By default these logos are written to the directory /usr/local/glassfish4/glassfish/domains/domain1/docroot/logos."

This issue hit me and some Red Hat interns a year or two ago when they were spinning up Dataverse on OpenShift.

I think we should fix this over on the Dataverse side somehow but I don't believe there's an issue (either one of you should feel free to open one) and I'm not sure what the fix would be. Put the logo in the database instead, base64 encoded? I'm definitely open to ideas. 😄

**Comment by wilkos-dans** [comment]
Hi @poikilotherm  & @pdurbin  Thanks for the feedback!
I understand the difficulties when "installing multiple Glassfish servers".
But this issue is about a step earlier, even on a 1 node cluster (=single Glassfish server).
It is about storing files inside a running Docker container, that will disappear when K8S manager decides to spin up a new Docker container, for whatever reason.
IMHO, I think the dataverse logos files ( logfiles?) should be persisted somewhere outside the running Docker container, just like the dataset files, which do persist between pods.

**Comment by 4tikhonov** [comment]
Hi @poikilotherm and @pdurbin, this issue is very important for us as Wilko already said. We have a customized version of Dataverse with subdataverses for different countries inside of our community and it's critical for them not to loose any logos or other adjustments after Docker containers will restart.

I did fixed this issue in @dataverse-docker repository with 2 extra Glassfish commands 
 /opt/glassfish4/glassfish/bin/asadmin delete-jvm-options '\-Ddataverse.files.directory=/opt/glassfish4/glassfish/domains/domain1/files'
 /opt/glassfish4/bin/asadmin create-jvm-options '\-Ddataverse.files.directory=/opt/glassfish4/glassfish/domains/domain1/docroot/files'

Persistent volume should be created on docroot folder to keep both files and logos
VOLUME /opt/glassfish4/glassfish/domains/domain1/docroot

The same goes for log files, what do you think?

**Comment by pdurbin** [comment]
I just dug through some old issues and `conf/openshift` but didn't find anything more than what I've written in this issue already.

@4tikhonov I'm not very familiar with VOLUME but I think your solution makes sense.

@wilkos-dans are you starting to call logo files "logfiles"? I find this a little confusing. 😄 And now @4tikhonov is talking about log files too?

If we want to talk about log files too, there's also the following note about Make Data Count files at http://guides.dataverse.org/en/4.14/installation/advanced.html#multiple-glassfish-servers

"If Make Data Count is used, its raw logs must be copied from each Glassfish server to single instance of Counter Processor. See also the :MDCLogPath database setting in the Configuration section of this guide and the Make Data Count section of the Admin Guide."

And there's a note for the files we added for https://github.com/IQSS/dataverse/issues/5145

"Dataset draft version logging occurs separately on each Glassfish server. See “Edit Draft Versions Logging” in the Monitoring section of the Admin Guide for details."

Finally, there's a note about sitemap.xml:

"When a sitemp is created by a Glassfish server it is written to the filesystem of just that Glassfish server. By default the sitemap is written to the directory /usr/local/glassfish4/glassfish/domains/domain1/docroot/sitemap."

I'm not sure how much of this is in scope for this issue, which is originally about logos.

I hope this comment adds clarity rather than confusion! 😄 

I have confidence that @poikilotherm will figure something out, especially since @4tikhonov seems to have already suggested a good fix for the logos issue. 😄

**Comment by poikilotherm** [comment]
Hey @wilkos-dans @4tikhonov and @pdurbin,

let's keep this issue dealing with logo persistance. Log files on K8s are a different topic, which should be discussed on its own, when you see a need. Feel free to open an issue for this, too.

About @4tikhonov suggestion to point `dataverse.files.directory` to the docroot of the domain: IMHO this is a bad idea. IIRC docroot is accessible to anyone accessing the server, so you might expose confident research data files that should not be exposed.

But as this is a free country: feel free to change the deployment object to mount the PVC to the docroot. Easily done with Kustomization. 

I still vote for changing the place where logos, sitemap etc are persisted. Any volunteers for opening an issue upstream?

**Comment by pdurbin** [comment]
> I still vote for changing the place where logos, sitemap etc are persisted. Any volunteers for opening an issue upstream?

This should be two separate upstream issues, please. One for sitemap.xml, one for dataverse logos. Thanks.

> IIRC docroot is accessible to anyone accessing the server, so you might expose confident research data files that should not be exposed.

I don't know if this is true or not but I can't find any information either way. I feel like I had to mess with a fair amount of stuff in these files...

- src/main/webapp/WEB-INF/glassfish-web.xml
- src/main/webapp/WEB-INF/pretty-config.xml

... to get sitemap.xml to show up at https://dataverse.example.com/sitemap.xml

Here's a screenshot from https://github.com/IQSS/dataverse/pull/5084

![Screen Shot 2019-06-14 at 10 44 18 AM](https://user-images.githubusercontent.com/21006/59517342-622c8e00-8e91-11e9-9713-03a9b2de56d5.png)

**Comment by pdurbin** [comment]
Yesterday in IRC, @poikilotherm said, "I am fiddling with moving it to /docroot in the container, so it will not be a blowup once changing to a different appserver using a different domain" http://irclog.iq.harvard.edu/dataverse/2019-10-16#i_108745

I'm fine with whatever works. 😄

**Comment by poikilotherm** [comment]
Heh - added my commits when you wrote that comment :smile: 
PR coming...

**Comment by pdurbin** [comment]
> Any volunteers for opening an issue upstream?

@DS-INRA just opened https://github.com/IQSS/dataverse/issues/6491

Should we move the conversation there?
