### ISSUE TITLE
Move from Travis CI to Community Jenkins

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#71]
The community uses https://jenkins.dataverse.org for different projects.
This project should move its CI testing from Travis to this service for sustainability.

**Comment by pdurbin** [comment]
Move or add?

https://github.com/AUSSDA/pyDataverse is tested on both Travis and Jenkins:

- Travis: https://travis-ci.com/AUSSDA/pyDataverse
- Jenkins: https://jenkins.dataverse.org/job/pyDataverse/

Why not both? 😄

**Comment by poikilotherm** [comment]
Simple: the GitHub Pull Request Plugin allows filtering pathes, so Image builds will only happen when images are affected. Kubernetes stuff will only be tested when it is affected. This is not easy to achieve with Travis...

**Comment by pdurbin** [comment]
> Hello World!

Since @poikilotherm have been talking about bots at http://irclog.iq.harvard.edu/dataverse/2019-06-27#i_99199 and I didn't know how he got @dataverse-bot to say something, I asked and he shared this screenshot:

![JarQT9e](https://user-images.githubusercontent.com/21006/60304776-64b6cb00-9908-11e9-889d-9d5e0468cf37.png)

Very cool stuff. I was telling him that I've seen commands `@glassfishrobot Run CI tests please` in pull requests at https://github.com/javaee/glassfish/pulls
